/**
 * build_attack_specs.js — merge authored+verified spec sets into
 * docs/js/attack_specs.js.
 *
 * The spec passes run as background workflows and dump their result JSON to a
 * task output file. This reads any number of those, merges by attack id (later
 * sources win, so a re-run of one boss replaces just that boss), sanity-checks
 * every assertion against the vocabulary spec_check.js actually implements, and
 * writes the browser-loadable file.
 *
 * Assertions that fail validation are DROPPED and reported, not silently kept:
 * an assertion referencing a kind or field the checker ignores would always
 * "pass", which is worse than not having it — it manufactures confidence.
 *
 *   node scripts/build_attack_specs.js <workflow-output.json> [...more]
 */
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, '..', 'docs', 'js', 'attack_specs.js');

const KINDS = {
  spawns: ['obj', 'byFrame', 'min', 'max'],
  absent: ['obj', 'byFrame'],
  count: ['obj', 'atFrame', 'min', 'max'],
  pos: ['obj', 'atFrame', 'x', 'y', 'tol'],
  ivar: ['obj', 'atFrame', 'name', 'eq', 'min', 'max', 'tol'],
  sprite: ['name', 'byFrame'],
  draw: ['name', 'atFrame', 'x', 'y', 'xscale', 'yscale', 'angle', 'alpha', 'minCalls', 'maxCalls', 'tol'],
  box: ['x', 'y', 'w', 'h', 'tol'],
  turntimer: ['eq', 'min', 'max', 'tol'],
};

function extractSpecs(file) {
  const raw = fs.readFileSync(file, 'utf8');
  let j;
  try { j = JSON.parse(raw); } catch (e) { console.log(`  ! ${path.basename(file)}: not JSON`); return []; }
  // Workflow output nests the script's return value under `result`.
  const r = j.result || j;
  const specs = r.specs || j.specs || [];
  if (r.changes && r.changes.length) {
    console.log(`  verification changed ${r.changes.length} assertion(s) in ${path.basename(file)}`);
  }
  return specs;
}

const files = process.argv.slice(2);
if (!files.length) {
  console.log('usage: node scripts/build_attack_specs.js <workflow-output.json> [...]');
  process.exit(1);
}

const byId = new Map();
for (const f of files) {
  console.log(`reading ${path.basename(f)}`);
  for (const s of extractSpecs(f)) {
    if (!s || !s.id || !Array.isArray(s.assertions)) continue;
    byId.set(s.id, s);
  }
}

// ── validate ───────────────────────────────────────────────────────────────
let kept = 0, dropped = 0;
const dropReasons = new Map();
const bump = k => dropReasons.set(k, (dropReasons.get(k) || 0) + 1);

for (const s of byId.values()) {
  s.assertions = s.assertions.filter(a => {
    if (!a || !a.kind || !KINDS[a.kind]) { bump('unknown kind: ' + (a && a.kind)); dropped++; return false; }
    if (!a.src) { bump('no src citation'); dropped++; return false; }
    // Must name its subject.
    if (['spawns', 'absent', 'count', 'pos', 'ivar'].includes(a.kind) && !a.obj) { bump(a.kind + ' without obj'); dropped++; return false; }
    if (['sprite', 'draw'].includes(a.kind) && !a.name) { bump(a.kind + ' without name'); dropped++; return false; }
    if (a.kind === 'ivar' && !a.name) { bump('ivar without name'); dropped++; return false; }
    // Must actually constrain something, or it passes vacuously.
    const params = KINDS[a.kind].filter(k => k !== 'obj' && k !== 'name' && k !== 'atFrame' && k !== 'byFrame' && k !== 'tol');
    if (!params.some(k => a[k] !== undefined && a[k] !== null)) {
      // spawns/absent/sprite are meaningful with no numeric params.
      if (!['spawns', 'absent', 'sprite'].includes(a.kind)) { bump(a.kind + ' constrains nothing'); dropped++; return false; }
    }
    kept++;
    return true;
  });
}

const specs = [...byId.values()].filter(s => s.assertions.length);

console.log(`\nattacks: ${specs.length}   assertions kept: ${kept}   dropped: ${dropped}`);
for (const [k, n] of [...dropReasons.entries()].sort((a, b) => b[1] - a[1])) {
  console.log(`  dropped ${n}x — ${k}`);
}
const kindTally = {};
for (const s of specs) for (const a of s.assertions) kindTally[a.kind] = (kindTally[a.kind] || 0) + 1;
console.log('by kind:', JSON.stringify(kindTally));

const header = `/**
 * attack_specs.js — GENERATED by scripts/build_attack_specs.js. Do not hand-edit;
 * regenerate from the spec workflow output instead.
 *
 * Per-attack assertions transcribed from the real DELTARUNE GML and consumed by
 * spec_check.js. Every assertion is a number the SOURCE STATES, carrying the
 * file and line it came from, so a failure can be argued with rather than
 * guessed at. Nothing here is a judgement about how an attack should feel.
 *
 * ${specs.length} attacks, ${kept} assertions.
 */
window.ATTACK_SPECS = `;

fs.writeFileSync(OUT, header + JSON.stringify(specs, null, 1) + ';\n');
console.log(`\nwrote ${OUT}`);
