/**
 * gen_object_index.js
 * Builds docs/js/gml_object_index.js from the REF DATA objects.tsv exports.
 *
 * Two things come out of this:
 *   1. index -> object name, per chapter. The decompiled GML contains raw object
 *      indices in places the decompiler couldn't resolve (e.g. `var target_obj = 1185;`
 *      then `target_obj.x`). objects.tsv row order IS asset index order, so
 *      line N of the file maps to index N-2.
 *   2. Object defaults GameMaker applies before Create runs: sprite_index,
 *      mask_index, parent (for event_inherited), depth, visible, persistent.
 */

const fs = require('fs');
const path = require('path');

const REF = 'C:/Users/lando/Desktop/DELTARUNE - REF DATA';
const OUT = path.join(__dirname, '..', 'docs', 'js', 'gml_object_index.js');

const CHAPTERS = [1, 2, 3, 4, 5];

function parseTsv(file) {
  const raw = fs.readFileSync(file, 'utf8').replace(/\r/g, '');
  const lines = raw.split('\n');
  const header = lines[0].split('\t');
  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i].length) continue; // trailing newline only
    const cells = lines[i].split('\t');
    const row = {};
    header.forEach((h, j) => { row[h] = (cells[j] || '').trim(); });
    rows.push(row);
  }
  return rows;
}

// Which sprites we have PNGs for. `spr_foo_3.png` -> `spr_foo`.
const SPRITE_DIR = path.join(__dirname, '..', 'docs', 'sprites');
const EXPORTED = new Set();
if (fs.existsSync(SPRITE_DIR)) {
  for (const f of fs.readdirSync(SPRITE_DIR)) {
    const m = f.match(/^(.*)_(\d+)\.png$/i);
    if (m) EXPORTED.add(m[1]);
  }
}

const chapters = {};
const spriteMeta = {};

for (const ch of CHAPTERS) {
  const dir = path.join(REF, `DELTARUNE Chapter ${ch} - REFDATA`);
  const objFile = path.join(dir, 'objects.tsv');
  if (!fs.existsSync(objFile)) { console.warn(`skip ch${ch}: no objects.tsv`); continue; }

  const rows = parseTsv(objFile);
  const names = rows.map(r => r.object);

  // Only record defaults that actually differ from GameMaker's blank defaults,
  // so the table stays small.
  const defs = {};
  rows.forEach(r => {
    const d = {};
    if (r.sprite) d.s = r.sprite;
    if (r.mask_sprite) d.m = r.mask_sprite;
    if (r.parent) d.p = r.parent;
    if (r.depth && Number(r.depth) !== 0) d.d = Number(r.depth);
    if (r.visible === 'False') d.v = 0;
    if (r.persistent === 'True') d.e = 1;
    if (Object.keys(d).length) defs[r.object] = d;
  });

  // Sprite frames/size/origin. Only kept for sprites we actually exported PNGs
  // for — the full table is ~24k rows across chapters and we can't draw the rest.
  const sprFile = path.join(dir, 'sprites.tsv');
  if (fs.existsSync(sprFile)) {
    for (const r of parseTsv(sprFile)) {
      if (!EXPORTED.has(r.sprite)) continue;
      spriteMeta[r.sprite] = [
        Number(r.frames) || 1, Number(r.width) || 0, Number(r.height) || 0,
        Number(r.originX) || 0, Number(r.originY) || 0,
      ];
    }
  }

  chapters[`ch${ch}`] = { names, defs };
  console.log(`ch${ch}: ${names.length} objects, ${Object.keys(defs).length} with defaults`);
}
console.log(`sprite meta for ${Object.keys(spriteMeta).length} exported sprites`);

// Names go out as newline-joined strings — far smaller than a JSON array of
// quoted strings, and split() at load is instant.
let out = `/**
 * gml_object_index.js — GENERATED by scripts/gen_object_index.js. Do not edit.
 *
 * Per-chapter asset tables extracted from the DELTARUNE REF DATA exports:
 *   objectNames[i] -> object name for raw asset index i. The decompiled GML
 *                     leaks these (e.g. \`var target_obj = 1185;\` then \`target_obj.x\`),
 *                     because objects.tsv row order IS asset index order.
 *   objectDefs[nm] -> { s: sprite, m: mask, p: parent, d: depth, v: visible, e: persistent }
 *                     i.e. the values GameMaker applies BEFORE the Create event runs.
 *   spriteMeta[nm] -> [frames, width, height, originX, originY] for exported sprites.
 */
(function(global) {
  'use strict';
  const NL = String.fromCharCode(10);
  const S = (s) => (s.length ? s.split(NL) : []);
  const CH = {};
`;

for (const [key, c] of Object.entries(chapters)) {
  out += `
  CH['${key}'] = {
    objectNames: S(${JSON.stringify(c.names.join('\n'))}),
    objectDefs: ${JSON.stringify(c.defs)},
  };
`;
}

out += `
  const SPRITE_META = ${JSON.stringify(spriteMeta)};

  for (const key of Object.keys(CH)) {
    const c = CH[key];
    c.objectIndex = new Map();
    c.objectNames.forEach((n, i) => { if (n) c.objectIndex.set(n, i); });
  }

  // Merged name -> defaults view. Chapters overwhelmingly agree on object
  // definitions; later chapters win a tie, and per-chapter tables stay
  // authoritative for numeric index resolution.
  const MERGED_DEFS = {};
  const OBJECT_SET = new Set();
  for (const key of ['ch1', 'ch2', 'ch3', 'ch4', 'ch5']) {
    if (!CH[key]) continue;
    Object.assign(MERGED_DEFS, CH[key].objectDefs);
    CH[key].objectNames.forEach(n => n && OBJECT_SET.add(n));
  }

  global.GML_OBJECT_INDEX = {
    chapters: CH,
    objectDefs: MERGED_DEFS,
    spriteMeta: SPRITE_META,

    /** Object name for a raw asset index. Chapter-specific — indices differ per chapter. */
    objectName(index, chapter) {
      const c = CH[chapter] || CH.ch3;
      return (c && c.objectNames[index]) || null;
    },

    /** Raw asset index for an object name, or -1. */
    objectIndexOf(name, chapter) {
      const c = CH[chapter] || CH.ch3;
      if (!c) return -1;
      const i = c.objectIndex.get(name);
      return i === undefined ? -1 : i;
    },

    /**
     * The state GameMaker gives a fresh instance before Create runs, resolved
     * through the parent chain (root -> leaf, so the most-derived value wins).
     */
    defaults(objectName, chapter) {
      const c = CH[chapter] || CH.ch3;
      const defs = (c && c.objectDefs) || MERGED_DEFS;
      const out = { sprite_index: '', mask_index: '', depth: 0, visible: true, persistent: false, parent: null };
      const chain = [];
      const guard = new Set();
      let nm = objectName;
      while (nm && defs[nm] && !guard.has(nm)) {
        guard.add(nm);
        chain.unshift(defs[nm]);
        nm = defs[nm].p;
      }
      for (const d of chain) {
        if (d.s) out.sprite_index = d.s;
        if (d.m) out.mask_index = d.m;
        if (d.d !== undefined) out.depth = d.d;
        if (d.v !== undefined) out.visible = !!d.v;
        if (d.e !== undefined) out.persistent = !!d.e;
      }
      const own = defs[objectName];
      out.parent = (own && own.p) || null;
      // GameMaker falls back to the sprite for the collision mask.
      if (!out.mask_index) out.mask_index = out.sprite_index;
      return out;
    },

    /** Full ancestor chain, nearest parent first. Drives event_inherited(). */
    parentChain(objectName, chapter) {
      const c = CH[chapter] || CH.ch3;
      const defs = (c && c.objectDefs) || MERGED_DEFS;
      const chain = [];
      const guard = new Set([objectName]);
      let nm = defs[objectName] && defs[objectName].p;
      while (nm && !guard.has(nm)) { guard.add(nm); chain.push(nm); nm = defs[nm] && defs[nm].p; }
      return chain;
    },

    /** True if \`child\` is \`ancestor\` or descends from it — GML's object_is_ancestor semantics. */
    isDescendantOf(child, ancestor, chapter) {
      if (child === ancestor) return true;
      return this.parentChain(child, chapter).indexOf(ancestor) !== -1;
    },

    isObject(name) { return OBJECT_SET.has(name); },
    frameCount(spriteName) { const m = SPRITE_META[spriteName]; return m ? m[0] : 0; },
    spriteSize(spriteName) { const m = SPRITE_META[spriteName]; return m ? { width: m[1], height: m[2] } : null; },
    origin(spriteName) { const m = SPRITE_META[spriteName]; return m ? { x: m[3], y: m[4] } : null; },
  };

})(typeof window !== 'undefined' ? window : globalThis);
`;

fs.writeFileSync(OUT, out, 'utf8');
console.log(`wrote ${OUT} (${(out.length / 1024).toFixed(1)} KB)`);

// NOTE: sprite_origins.js is deliberately NOT written here.
// scripts/sync_sprites.js owns it, because origins must come from the SAME chapter
// as the copied art — a merged table silently offsets sprites that differ between
// chapters. Run sync_sprites.js after this script.
