/**
 * gen_object_depths.js — build docs/js/gml_object_depths.js
 *
 * DELTARUNE's real per-object depths are NOT in objects.tsv. That export's depth
 * column is 0 for every object in every chapter, because the game does not use
 * the room-editor depth at all: it is a GameMaker Studio 1 project upgraded to
 * GMS2, and it keeps its depths in the GMS1-compat table built by
 * gml_GlobalScript___global_object_depths.gml:
 *
 *     global.__objectDepths[186] = 5;
 *     global.__objectNames[186]  = "obj_growtangle";
 *     ... then __objectID2Depth[asset_get_index(name)] = depth
 *
 * and DELTARUNE's own instance_create is a GlobalScript that stamps it:
 *
 *     function instance_create(arg0, arg1, arg2) {
 *         var myDepth = object_get_depth(arg2);
 *         return instance_create_depth(arg0, arg1, myDepth, arg2);
 *     }
 *
 * So EVERY instance is born at its table depth. Without this table the whole
 * battle renders at depth 0 and the draw order collapses onto the tie-break,
 * which is how the Stars cone ended up UNDER the battle box: obj_fake_gt (the
 * object that actually draws the box during that attack) is created inside the
 * cone's own Create, so it always has a higher instance id and always won.
 * With real depths the box is 5, the soul is 1 and the cone is 0 — the cone
 * draws last, on top, exactly as the attack intends (it even subtracts the soul
 * out of its light, which only makes sense when the light is above the soul).
 *
 * object_get_depth is a FLAT per-object-index lookup with NO parent walk, so an
 * object missing from the 235-entry table really is depth 0 even when its parent
 * has a depth (obj_knight_pointing_starchild does not inherit obj_regularbullet's
 * -10). This generator reproduces that exactly: absent means absent.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const GML_ROOT = 'C:/Users/lando/Desktop/DELTARUNE - GML';
const OUT = path.join(__dirname, '..', 'docs', 'js', 'gml_object_depths.js');

const out = {};
const stats = [];

for (let c = 1; c <= 5; c++) {
  const file = path.join(GML_ROOT, `DELTARUNE Chapter ${c} - GML`,
    'gml_GlobalScript___global_object_depths.gml');
  if (!fs.existsSync(file)) { stats.push(`ch${c}: (no table)`); continue; }
  const src = fs.readFileSync(file, 'utf8');

  const depths = {};
  for (const m of src.matchAll(/__objectDepths\[(\d+)\]\s*=\s*(-?\d+)/g)) {
    depths[m[1]] = Number(m[2]);
  }
  const names = {};
  for (const m of src.matchAll(/__objectNames\[(\d+)\]\s*=\s*"([^"]+)"/g)) {
    names[m[1]] = m[2];
  }

  const map = {};
  for (const idx of Object.keys(names)) {
    if (depths[idx] === undefined) continue;
    // Later entries win, matching the loop's assignment order.
    map[names[idx]] = depths[idx];
  }
  out['ch' + c] = map;
  stats.push(`ch${c}: ${Object.keys(map).length} objects`);
}

const banner = `/**
 * gml_object_depths.js — GENERATED by scripts/gen_object_depths.js. Do not edit.
 *
 * objectName -> the depth DELTARUNE's instance_create() stamps at spawn, read
 * from each chapter's __global_object_depths() table. objects.tsv's depth column
 * is zero for every object and is NOT the real value.
 *
 * A name ABSENT from a chapter's map is genuinely depth 0: object_get_depth is a
 * flat index lookup with no parent inheritance.
 *
 * Battle reference (ch3): obj_darkener 200, obj_monsterparent 90, obj_growtangle 5,
 * obj_battlecontroller 5, obj_grazebox 2, obj_heart 1, obj_bulletparent 0,
 * obj_regularbullet -10. Lower depth draws in FRONT.
 */
`;

fs.writeFileSync(OUT, banner + 'window.GML_OBJECT_DEPTHS = ' + JSON.stringify(out) + ';\n');
console.log('gml_object_depths.js written —', stats.join(', '));
