/**
 * gen_sprite_indices.js — resolve RAW NUMERIC asset indices to sprite names.
 *
 * The decompiled dump often stores a sprite as the integer the compiler assigned
 * it rather than its name:
 *
 *     pinkportrait = 982;          // spr_pinkspeaker_shocked_origin_adjusted
 *     knight_sprite = 664;         // spr_roaringknight_front
 *
 * Our engine identifies every sprite by NAME, and every draw path bails on a
 * non-string, so each of those draws was silently dropped — all 30 of the dating
 * minigame's portraits, and the Knight's body during the roar.
 *
 * The mapping is recoverable because sprites.tsv preserves the project's asset
 * order: index N is data row N (file line N + 2, after the header). Verified
 * against sprites whose index appears next to a name in the GML — 982 and 2588
 * sit beside `sprite_set_offset(spr_pinkspeaker_shocked_origin_adjusted, ...)`
 * and `spr_pinkspeaker_date4_idle`, and 664/219/4961/4319 match the Knight's
 * front/roar/flourish/slash sprites used around them.
 *
 * Writes docs/js/sprite_indices.js: { ch1: {index: name}, ... }.
 */

const fs = require('fs');
const path = require('path');

const REF_ROOT = 'C:/Users/lando/Desktop/DELTARUNE - REF DATA';
const OUT = path.join(__dirname, '..', 'docs', 'js', 'sprite_indices.js');

const byChapter = {};
let total = 0;

for (let n = 1; n <= 5; n++) {
  const tsv = path.join(REF_ROOT, `DELTARUNE Chapter ${n} - REFDATA`, 'sprites.tsv');
  if (!fs.existsSync(tsv)) continue;
  const lines = fs.readFileSync(tsv, 'utf8').split(/\r?\n/);
  const table = {};
  // Line 0 is the header; data row i therefore carries asset index i.
  for (let i = 1; i < lines.length; i++) {
    const name = lines[i].split('\t')[0];
    if (!name) continue;
    table[i - 1] = name;
  }
  byChapter['ch' + n] = table;
  total += Object.keys(table).length;
  console.log(`ch${n}: ${Object.keys(table).length} sprite indices`);
}

// Spot-check the anchors we verified by hand, so a re-export that changes row
// order fails loudly here instead of silently mis-drawing every portrait.
const CHECKS = [
  ['ch5', 982, 'spr_pinkspeaker_shocked_origin_adjusted'],
  ['ch5', 2588, 'spr_pinkspeaker_date4_idle'],
  ['ch3', 664, 'spr_roaringknight_front'],
];
let bad = 0;
for (const [ch, idx, expect] of CHECKS) {
  const got = byChapter[ch] && byChapter[ch][idx];
  if (got !== expect) {
    console.error(`  MISMATCH ${ch}[${idx}] = ${got}, expected ${expect}`);
    bad++;
  }
}
console.log(bad ? `\n${bad} anchor check(s) FAILED — asset order may have changed` : '\nanchor checks: all pass');

const src = `/**
 * sprite_indices.js — GENERATED by scripts/gen_sprite_indices.js. Do not edit.
 *
 * Asset index -> sprite name, per chapter. The decompiled GML stores some
 * sprites as raw integers; every draw path resolves them through this table.
 */
window.GML_SPRITE_INDICES = ${JSON.stringify(byChapter)};
`;
fs.writeFileSync(OUT, src, 'utf8');
console.log(`\nwrote ${OUT} (${(src.length / 1024).toFixed(1)} KB, ${total} indices)`);
