/**
 * gen_sounds.js — copy every sound the shipped GML references into docs/sounds/
 * and write the manifest gml_audio.js plays from.
 *
 * Sound names are validated against each chapter's sounds.tsv (`sound` column),
 * which also supplies the filename and authored volume. That filter is what
 * separates real sound assets (snd_bomb) from the snd_* GlobalScript FUNCTIONS
 * (snd_play, snd_volume, ...) that a raw regex would also match.
 *
 * Chapter priority mirrors the sprite sync: ch3, ch2, ch4, ch5, ch1.
 */

const fs = require('fs');
const path = require('path');

const EXPORT_ROOT = 'C:/Users/lando/Desktop/DELTARUNE - EXPORT';
const REF_ROOT = 'C:/Users/lando/Desktop/DELTARUNE - REF DATA';
const DOCS = path.join(__dirname, '..', 'docs');
const JS = path.join(DOCS, 'js');
const OUT_DIR = path.join(DOCS, 'sounds');

const CHAPTER_PRIORITY = ['ch3', 'ch2', 'ch4', 'ch5', 'ch1'];
const CH_NUM = { ch1: 1, ch2: 2, ch3: 3, ch4: 4, ch5: 5 };

// ── per-chapter sound tables from sounds.tsv ────────────────────────────────
const tables = {};
for (const [ch, n] of Object.entries(CH_NUM)) {
  const tsv = path.join(REF_ROOT, `DELTARUNE Chapter ${n} - REFDATA`, 'sounds.tsv');
  if (!fs.existsSync(tsv)) continue;
  const lines = fs.readFileSync(tsv, 'utf8').replace(/\r/g, '').split('\n');
  const header = lines[0].split('\t');
  const iName = header.indexOf('sound'), iFile = header.indexOf('file'), iVol = header.indexOf('volume');
  const map = new Map();
  for (let i = 1; i < lines.length; i++) {
    if (!lines[i]) continue;
    const c = lines[i].split('\t');
    map.set(c[iName], { file: c[iFile], volume: Number(c[iVol]) || 1 });
  }
  tables[ch] = map;
}

// ── names referenced by the shipped GML ─────────────────────────────────────
const referenced = new Set();
for (const f of ['gml_presets.js', 'gml_scripts.js', 'gml_objects.js']) {
  const p = path.join(JS, f);
  if (!fs.existsSync(p)) continue;
  const src = fs.readFileSync(p, 'utf8');
  const re = /\b(?:snd|mus|audio|AUDIO)_[a-zA-Z0-9_]+\b/g;
  let m;
  while ((m = re.exec(src))) referenced.add(m[0]);
}
console.log(`sound-shaped identifiers referenced: ${referenced.size}`);

// ── resolve against the tables, chapter priority ───────────────────────────
if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });
const manifest = {};
let copied = 0, missingFile = 0;
const perChapter = {};

for (const name of [...referenced].sort()) {
  let picked = null;
  for (const ch of CHAPTER_PRIORITY) {
    const t = tables[ch];
    if (!t || !t.has(name)) continue;
    const entry = t.get(name);
    const dir = path.join(EXPORT_ROOT, `DELTARUNE Chapter ${CH_NUM[ch]} - EXPORT`, 'sounds');
    // The tsv `file` column carries no extension; the export writes
    // <name>.wav or <name>.ogg. Try the likely spellings.
    const base = entry.file || name;
    let src = null;
    for (const cand of [base, base + '.wav', base + '.ogg', name + '.wav', name + '.ogg']) {
      const p = path.join(dir, cand);
      if (cand && fs.existsSync(p)) { src = p; break; }
    }
    if (!src) continue;
    picked = { ch, entry, src };
    break;
  }
  if (!picked) continue;   // a function name or a sound with no exported file

  // Output name keyed by the SOUND name so two chapters' same-named files
  // can't collide; keep the original extension.
  const ext = path.extname(picked.entry.file) || '.ogg';
  const outName = name + ext;
  try {
    fs.copyFileSync(picked.src, path.join(OUT_DIR, outName));
    manifest[name] = { file: outName, volume: picked.entry.volume };
    perChapter[picked.ch] = (perChapter[picked.ch] || 0) + 1;
    copied++;
  } catch (e) { missingFile++; }
}

console.log(`copied ${copied} sound files into docs/sounds/ (${missingFile} unreadable)`);
console.log('per chapter:', JSON.stringify(perChapter));

const src = `/**
 * gml_sounds.js — GENERATED by scripts/gen_sounds.js. Do not edit.
 * soundName -> { file (under docs/sounds/), volume (authored gain) }.
 */
window.GML_SOUND_MANIFEST = ${JSON.stringify(manifest, null, 0)};
`;
fs.writeFileSync(path.join(JS, 'gml_sounds.js'), src, 'utf8');
console.log(`wrote docs/js/gml_sounds.js (${Object.keys(manifest).length} sounds)`);
