/**
 * gen_sprite_trims.js — build docs/js/sprite_trims.js.
 *
 * The EXPORT art is TRIMMED: transparent margins were removed, and the margin
 * offsets were not exported anywhere. REF DATA still records the true canvas
 * (w, h) and origin per chapter, so a sprite like spr_donut_bullet reports a
 * 48x50 canvas with a dead-centre origin (24,25) while its PNG is 24x25 —
 * drawn at (-ox, -oy) the art hangs entirely up-left of the instance.
 *
 * We cannot recover asymmetric margins, so we only repair the recoverable
 * case: sprites whose origin sits at the canvas CENTRE (±1px). Bullet and
 * effect art with a centred origin is drawn symmetric about that centre, so
 * re-centring the trimmed rect inside the true canvas reproduces the original
 * placement exactly. Everything else is left untouched rather than guessed.
 *
 * Output: window.GML_SPRITE_TRIMS = { name: [[dx, dy], ...] per frame }
 * where (dx, dy) is the trimmed art's top-left inside the true canvas.
 * Consumed by gml_asset_db.drawSprite AND gml_helpers maskGeom — draw and
 * collision must shift together or hitboxes detach from pixels.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const REF = 'C:/Users/lando/Desktop/DELTARUNE - REF DATA';

function pngSize(p) {
  const b = fs.readFileSync(p);
  return [b.readUInt32BE(16), b.readUInt32BE(20)];
}

// REF DATA rows per chapter: name \t frames \t w \t h \t ox \t oy
const refByCh = {};
for (let c = 1; c <= 5; c++) {
  const p = `${REF}/DELTARUNE Chapter ${c} - REFDATA/sprites.tsv`;
  if (!fs.existsSync(p)) continue;
  const map = {};
  for (const line of fs.readFileSync(p, 'utf8').split('\n')) {
    const t = line.trim().split('\t');
    if (t.length >= 6) map[t[0]] = { w: +t[2], h: +t[3], ox: +t[4], oy: +t[5] };
  }
  refByCh[c] = map;
}

const readTable = (file, marker) => {
  // Files may hold several `window.X = {...};` tables — cut at the first `};`.
  const s = fs.readFileSync(path.join(ROOT, file), 'utf8');
  const start = s.indexOf('{', s.indexOf(marker));
  const end = s.indexOf('};', start);
  return JSON.parse(s.slice(start, end + 1));
};
const manifest = readTable('docs/js/sprite_manifest.js', 'GML_SPRITE_MANIFEST');
const origins = readTable('docs/js/sprite_origins.js', 'GML_SPRITE_ORIGINS');

const trims = {};
const stats = { sprites: 0, frames: 0, skippedOffCentre: 0, skippedAmbiguous: 0 };

for (const [name, files] of Object.entries(manifest)) {
  const org = origins[name];
  if (!org) continue;

  // Pin the chapter whose origin matches the shipped origin — sync_sprites
  // copied art and origin from the same chapter, so this identifies the
  // canvas that art belongs to. Require all matching chapters to agree.
  let canvas = null, ambiguous = false;
  for (let c = 1; c <= 5; c++) {
    const r = refByCh[c] && refByCh[c][name];
    if (!r || r.ox !== org[0] || r.oy !== org[1]) continue;
    if (!canvas) canvas = r;
    else if (canvas.w !== r.w || canvas.h !== r.h) ambiguous = true;
  }
  if (!canvas) continue;
  if (ambiguous) { stats.skippedAmbiguous++; continue; }

  // Only centred origins are recoverable (symmetric trim).
  if (Math.abs(canvas.ox - canvas.w / 2) > 1 || Math.abs(canvas.oy - canvas.h / 2) > 1) {
    stats.skippedOffCentre++;
    continue;
  }

  let any = false;
  const perFrame = files.map(f => {
    const p = path.join(ROOT, 'docs/sprites', f);
    if (!fs.existsSync(p)) return [0, 0];
    const [pw, ph] = pngSize(p);
    if (pw >= canvas.w && ph >= canvas.h) return [0, 0];
    const dx = Math.max(0, Math.floor((canvas.w - pw) / 2));
    const dy = Math.max(0, Math.floor((canvas.h - ph) / 2));
    if (dx || dy) { any = true; stats.frames++; }
    return [dx, dy];
  });
  if (any) { trims[name] = perFrame; stats.sprites++; }
}

const out = `/**
 * sprite_trims.js — GENERATED by scripts/gen_sprite_trims.js. Do not edit.
 *
 * Per-frame [dx, dy]: where the TRIMMED export art sits inside the sprite's
 * true canvas (REF DATA w/h). Only centred-origin sprites are listed — the
 * symmetric-trim case that can be reconstructed exactly. drawSprite and
 * maskGeom both apply these so pixels and hitboxes stay glued together.
 */
window.GML_SPRITE_TRIMS = ${JSON.stringify(trims)};
`;
fs.writeFileSync(path.join(ROOT, 'docs/js/sprite_trims.js'), out);
console.log('sprite_trims.js written:', JSON.stringify(stats));
